name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - service
          - api-messages
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Modify .npmrc
        run: echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> .npmrc
      - name: Install dependencies
        run: npm install
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Modify .npmrc
        run: rm .npmrc
      - name: Build packages
        run: npx lerna run build
      - name: Run tests
        working-directory: ./packages/${{ matrix.package }}
        run: npm test
      - name: Submit code coverage
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.package }}
          directory: ${{ github.workspace }}/packages/${{ matrix.package }}/coverage
